---
  name: Manual Build
  on: workflow_dispatch
  
  concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
  
  jobs:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - uses: actions/setup-python@v5
          with:
            python-version: "3.11.9"
  
        - name: Install Poetry Action
          uses: snok/install-poetry@v1.3.1
          with:
            virtualenvs-create: true
            virtualenvs-in-project: true
  
        - name: Load cached venv
          id: cached-poetry-dependencies
          uses: actions/cache@v4
          with:
            path: .venv
            key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-2
  
        - uses: FedericoCarboni/setup-ffmpeg@v3.1
          id: setup-ffmpeg
          with:
            ffmpeg-version: release
            architecture: 'x64'
            github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  
        - name: Install dependencies
          run: poetry install
  
        - name: Bundle
          run: poetry run make bundle_windows
          shell: bash
  
        - uses: actions/upload-artifact@v4
          with:
            name: Buzz-windows
            path: dist/Buzz*-windows.exe
  